version: '3.9'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fast_api_cinema
    volumes:
       - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"

  backend:
    build: .
    command: 'uvicorn main:app --host 0.0.0.0 --reload'
    environment:
      DB_URL: postgresql://cinema:password@db:5432/fast_api_cinema
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - "db:db"

  # rabbitMQ:
  #     image: "rabbitmq:3-management"
  #     hostname: "my-rabbit"
  #     environment:
  #       RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
  #       RABBITMQ_DEFAULT_USER: "rabbitmq"
  #       RABBITMQ_DEFAULT_PASS: "rabbitmq"
  #     ports:
  #       - "15672:15672"
  #       - "5672:5672"  