version: '3.9'
services:
  backend:
    build: .
    command: 'uvicorn blog.main:app --host 0.0.0.0'
    ports:
      - 8000:8000
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: cinema
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fast_api_cinema
    volumes:
       - /private/var/lib/postgresql:/var/lib/postgresql
    ports:
      - "5433:5432"